language: node_js
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: VJpUpcE/UbGpPjbF5aDU6no+5qSbqXqfr/75+Y1rVH3OlSVT/2nig2deloPik5OwBplC0VtEdC9XnMXU3dk0MKwecmKeJOp1oGg8wLEreLaQcyxI28mGBZUY+YeHmNZaq8S6CfxsrH3Sesp3og50WIIUMhIQwmgHwNZRrQd50A8=
